import{S as m,N as p,A as g}from"./assets/vendor-D7M8BDcB.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();new m(".my-swiper",{modules:[p,g],loop:!0,speed:800,autoplay:{delay:3e3,disableOnInteraction:!1},navigation:{nextEl:".gallery-button-next",prevEl:".gallery-button-prev"},slidesPerView:1.2,spaceBetween:16,breakpoints:{1440:{slidesPerView:3.4,spaceBetween:24}}});document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),i=l.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 7H19M5 17H19M5 12H19" stroke="#3E3B3A" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 6L11.75 11.75M11.75 11.75L6 17.5M11.75 11.75L17.5 17.5M11.75 11.75L17.5 6" stroke="#3E3B3A" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;l.addEventListener("click",()=>{t=!t,i.innerHTML=t?o:c,t?n():r()}),a.forEach(d=>d.addEventListener("click",()=>{r(),i.innerHTML=c,t=!1})),window.addEventListener("scroll",s);function n(){u.style.display="block"}function r(){u.style.display="none"}function s(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function i(o){const n=document.getElementById(o);if(!n)return;const r=l(),s=n.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:s,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const r=this.getAttribute("href");if(!r)return;const[s,d]=r.split("#");if(!d)return;const f=window.location.pathname.split("/").pop();!(s===""||s==="./"||s===f||s==="./"+f)||!document.getElementById(d)||(n.preventDefault(),i(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(r=>r.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function c(){const o=window.pageYOffset+l()+100;a.forEach(n=>{const r=n.offsetTop,s=r+n.offsetHeight;o>=r&&o<s&&t(n.id)})}if(window.addEventListener("scroll",c),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{i(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
